title: Diversity in Tech
description: >
  LEARN the language of shared experience. 
  DISCOVER what guided them to make a difference.
  Connect and FEEL represented.
minima:
  social_links:
    twitter: diverseintech
author:
  email: paciej00@gmail.com
url: "https://diversityin-tech.github.io"
twitter_username: diverseintech
google_analytics: UA-173531993-1
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
